# Generated by Django 3.2.8 on 2021-10-08 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0002_auto_20211008_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='book',
        ),
        migrations.RemoveField(
            model_name='book',
            name='location',
        ),
    ]
