# Generated by Django 3.2.8 on 2021-10-09 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0003_auto_20211008_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='locations',
            new_name='location',
        ),
    ]
